# .github/release.yml

changelog:
  exclude:
    authors:
      - dependabot
      - pre-commit-ci
  categories:
    - title: Features
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
    - title: Dependencies
      labels:
        - dependencies
