# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

formats: [ ]

python:
  install:
    - requirements: requirements_dev.txt
    - requirements: requirements.txt
    - method: pip
      path: .
