checks:
    python:
        code_rating: true
        duplicate_code: true
build:
    environment:
        python: '3.7.1'
    dependencies:
        # Runs before inferred commands
        before:
            - pip install -r requirements_dev.txt
    nodes:
        analysis:
            project_setup:
                override:
                    - "true"
            tests:
                override:
                    - py-scrutinizer-run
                    - command: pylint-run
                      use_website_config: true
            environment:
                node:
                    version: 6.0.0
        tests: true
filter:
    excluded_paths:
        - "/tests/*"
    dependency_paths:
        - "lib/*"
