language: python
os:
    - linux
python:
    - "3.6"
    - "3.7"
install:
    - pip install -U pip
    - pip install -U tox-travis
    - pip install -U .

script:
    - pip install -U -r requirements_dev.txt 2>&1 | tail -n 11
    - pip install -U numpy  # needed for linspace with vectors
    - echo "TensorFlow version:" && pip install coverage 2>&1 | tail -n 11
    - python -c 'import tensorflow as tf; print(tf.__version__)'
    - coverage run --source=/home/travis/build/zfit/ --omit=".tox/*,*/test*,*/minimizers/interface.py,*/core/testing.py" --branch -m py.test --basetemp={envtmpdir}
    - coverage report
    - bash utils/ci/test_examples.sh
    - bash utils/ci/test_tutorials.sh
    - bash utils/ci/testbuild_docs.sh
    - bash utils/ci/testbuild_package.sh

after_success:
    - pip install coveralls
    - coveralls

deploy:
    - provider: pypi
      distributions: sdist bdist_wheel
      user: zfit
      password:
          secure: ZNNpI3RKnGZrkitcVZScG6EXO7elIJuxY5b8HvjBTz9wR4ufUSG2klFlgMcZKJAbCZ/upKLPnfje3cxmkfhnN8PBVViO39JHX4g35OvUxMRFp3XthAh6f0jfFceK41F1dk8RjL3nhz4EADmupeYsd13RmxM4OqZhfEbwM2I7jQF7+Wnc4vcG6iSeBnTbIt+B3r9v++l1y9On8rKgfac9t+G+dTKDs8HSDrHWa54re1XAa5cpFeArbBX3f4dQkjFI1nY3aZ1JbJVp4ew0avYjzfTLpdVrdKqHAyY5YIO97Uk4X7GKSZK2PZ8yTQGmtfE54rz6y/PdV4e7CRieP0FsOSVYZ7dFneGTu35wltZXr/hu9Tmn57/Qs+4XEcTrcw0jPExVTAkXnvGYQeew0ut9tmeV5J7Ghx2SLyjVEw3DSsulA8mRLP+d1XBSCg4yIsx17kqhCPJ76DvMFwpVwzpTUzLQbZAHw0+RY1pc7eQO0VwSmnStkxS8JnIuCZ7pQgPkMBtGPlqkEALSg06tOhbGafvye//w9c48N2Ns4+9MJT1PPmsDoXRRt1ffY8+69v8s3ykuIcx9N7Dze/BKQE5PPTiaR/RhRwpcTZsgNeizEpUt3Xh1SxO+QGQ1DWJKXKbAc+DkzATwCciRJS/plk224rG9Wk7c26p9FhGypSQgAZs=
      on:
          branch: master
          tags: true
          repo: zfit/zfit
          python: 3.7

    - provider: pages
      skip_cleanup: true
      github_token:
          secure: jrPIzI6e67nPuqIFXCwr0NfpAKxVrkZ5JSE9iW7GLVagLTiHcXCnzGDDPYo8Aq+jwJv69Hy+wXLCgq5G6AU/SCy9eLjYlAFVoEwyKh9SQzm404ay3B5Gxcuskj4nqJWWWH0ETAK4QIvhWtAzx48ElNwLOaidzPRFAgyzSVm337EpnEvuNr67I53M0IYaaAL21zWj8yCdKzOTOg/GI1Idn3a1cvW+Hqy0AWID7d/LxNWC1zwBIwTwUGaMUOw9tA2FTqrXXbfW00nBlulhYkkWG3JUursL8nrs/PLzwp5lJPQJ8DBG6I1PYexZ5Cfl6GMHY6+K2lSx+PdNeB9UkEucXNiB4utQMplCqVxHPi/m2wEM9tJSADMQ96HCKSprXmKfa1VW039Dxf8efWGosO7dI1QOmbsrs8LcloSLli/q+PmgNv7s+emEv6/X0UL7idB4T097KPsJCulE468VBwuNfnvIUcX2a2q7T+MDr6Q3uDFZ1NYAsTPpOLqDLM25ri5h0DHf0i3h3wCuMT27kDUlpEcSjaVeJvJStlS3nn+ioo/LGNUGvNiO9uUYB62Pegb8RmIEZ1QGjL6hhGPujv9WAdqYU2f8iSmpBr50G/jOUZhnOMOcvttaQDew20+TRvg20u43HggaeS9f32YbXEK7QbtdtGLsJiPculnxF3ZNBmM=
      local_dir: docs/_build/html
      keep-history: true
      on:
          branch: develop
          condition: $TRAVIS_PYTHON_VERSION = "3.7" && $TRAVIS_OS_NAME = "linux"


